import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="flex flex-col min-h-screen container" >
      <Header />

        <main className="flex-1" >
        {children}
        </main>


        </div>

      </body>
    </html>
  );
}
